trigger: none

resources:
  repositories:
    - repository: pipelineTemplateRepository
      type: github
      name: emmanuelbenitez/Be.Stateless.Build.Agent.Yaml.Pipeline.Templates
      ref: refs/heads/cleanup-code
      endpoint: github.com_icraftsoftware

extends:
  template: Pipelines/net/manual-release.yml@pipelineTemplateRepository
  parameters:
    Major: 2
    Minor: 0
